### ISSUE TITLE
An internal error occured while executing the command

### ISSUE THREAD

**Issue by ghost** [steve4744/ParkourTopTen#3]
I am having issues using the plugin here's the pastebin link for the error

https://pastebin.com/cXhGHtS6

**Comment by ghost** [comment]
I installed the 1.12.2 version of the plugin but i am getting this error
https://pastebin.com/RgwcWiT8

**Comment by steve4744** [comment]
As you've realised, version 4.0 of the plugin is only supported on 1.17.1+ as the first error shows the Bukkit blockdata method doesn't exist in 1.12.

The version for 1.12 was written for Parkour 5.3 so is incompatible with the latest version of Parkour which is 7.0.6 (as the Parkour code base changed a lot in version 6.0 and then big changes again in Version 7.0).

I'll have a look at what's needed to update the old version to support Parkour 7.0+

**Comment by ghost** [comment]
Thank you

**Comment by steve4744** [comment]
The legacy version has been updated to support Parkour 7.x.
Version 1.4.2 can be download here: https://github.com/steve4744/ParkourTopTen/releases
